### ISSUE TITLE
ES6 JavaScript request

### ISSUE THREAD

**Issue by sylwesterdigital** [meta-quest/immersive-web-emulation-runtime#1]
Hi Felix,

I hope this message finds you well.

First, I want to thank you for all the hard work and dedication you've put into maintaining this project. It's been incredibly helpful for many of us in the community.

I am writing to ask if it would be possible to provide a version of the codebase written in ES6 JavaScript instead of TypeScript. While TypeScript offers many benefits, some developers, including myself, prefer working directly with ES6 for various reasons, including familiarity and specific project requirements.

Having an ES6 version would greatly facilitate my work and likely benefit others in the community who share this preference. I understand this might be a significant request, and I truly appreciate any consideration you can give to it.

Thank you once again for your time and effort. Looking forward to your response.

Best regards,

**Comment by felixtrz** [comment]
Hey @sylwesterdigital,

Thank you for your interest in this project and for your kind words!

Are you looking to use/extend IWER in your projects, or are you intending to contribute to the codebase of IWER?

If you are looking to use or extend IWER in your projects, you can seamlessly integrate it with your ES6 projects. In fact, the example project (located in the `/example` folder) uses ES module JavaScript instead of TypeScript. You can install IWER directly from NPM with the following command:

```bash
npm install iwer
```

Additionally, we have made a UMD build available, which you can access through these links:
- [iwer.js](https://www.unpkg.com/iwer@1.0.0/build/iwer.js)
- [iwer.min.js](https://www.unpkg.com/iwer@1.0.0/build/iwer.min.js) (minified version)

**Comment by felixtrz** [comment]
If you intend to contribute to IWER, you will need to work with TypeScript. I've chosen TypeScript for this project because I want to make this library type-safe and less error-prone, and we are unlikely to move away from TypeScript for IWER in the foreseeable future.

However, if you need a feature but don't want to write and ship TypeScript code directly into IWER, simply open an issue requesting that feature! If there is enough interest from the community, we will make sure to add it to our roadmap.

If you have any more questions or need further assistance, feel free to ask. We're here to help!

Best regards,

Felix

**Comment by felixtrz** [comment]
Marking issue as closed
